import {Platform, StyleSheet} from 'react-native';
import {color} from '../../config/color';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {getPx} from 'styled-system';

export const styles = StyleSheet.create({
  main: {
    backgroundColor: color.defaultBackgroundColor,
  },

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FFDDC9',
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 3},
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 21,
    height: hp(Platform?.OS == 'ios' ? '10' : '7'),
    alignItems: 'center',
  },
  te: {
    textAlign: 'center',
    fontSize: hp('2'),
    color: '#512500',
    fontWeight: 'bold',
    marginTop: hp(Platform?.OS == 'ios' ? '4' : '0'),
    marginLeft: wp('3'),
  },
  icon: {
    marginTop: hp(Platform?.OS == 'ios' ? '4' : '0'),
    marginLeft: wp('3'),
  },
  box: {
    padding: 13,
    marginTop: 20,
    backgroundColor: '#F3F5F7',
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 3},
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 5,
    borderRadius: 10,
  },
  container: {
    borderWidth: 0,
  },
  imm: {
    width: wp('88%'),
    height: hp('40.7'),
    borderRadius: Platform.OS == 'android' ? 5 : 20,
  },
  tep: {
    color: '#512500',
    fontSize: 14,
    marginTop: hp('0.5%'),
  },
  carttouch: {
    backgroundColor: '#E9691D',
    width: wp('60%'),
    height: hp('7%'),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  buttonParent: {
    width: wp('75%'),
    height: hp('7%'),
    alignSelf: 'center',
    backgroundColor: '#E0998A',
    flexDirection: 'row',
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: hp(Platform?.OS == 'ios' ? '3' : '0'),
  },
  delvery: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#919191',
    marginTop: 20,
  },
  stock: {
    color: 'red',
    fontSize: 30,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  optionsContainer: {
    width: wp('90%'),
    height: 'auto',
    paddingBottom: hp('5'),
    backgroundColor: '#F3F5F7',
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: hp('2'),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 3},
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 5,
  },
  pickerStyle: {
    width: wp('80'),
    height: hp(Platform?.OS == 'ios' ? '20' : '7'),
    color: '#512500',
    backgroundColor: Platform?.OS == 'ios' ? 'transparent' : '#FFDDC9',
    alignSelf: 'center',
    overflow: 'hidden',
  },
  pickerParentStyle: {
    width: wp('80'),
    height: hp(Platform?.OS == 'ios' ? '20' : '7'),
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: hp(Platform?.OS == 'ios' ? '-5' : '2'),
    alignItems: 'center',
    justifyContent: 'center',
    color: '#512500',
  },
  attributeText: {
    color: '#512500',
    fontSize: hp('2'),
    marginTop: hp('2'),
  },

  favButton: {
    width: wp('15'),
    height: hp('7'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentTextContainer: {
    width: wp('88%'),
    height: hp('5%'),
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  bottomImageScroller: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: wp('2'),
    marginTop: hp('3%'),
  },
  sliderText: {
    fontSize: hp('2%'),
    color: color.themColorPrimary,
  },
  bottomimages: {
    borderColor: 'black',
    borderRadius: 10,
    borderWidth: 1,
    marginRight: 10,
  },
  imagss: {
    width: wp('27%'),
    height: hp('15%'),
    borderRadius: 10,
  },
  submitreviews: {
    backgroundColor: color.themColorPrimary,
    textAlign: 'center',
    width: wp('50'),
    alignSelf: 'center',
    height: hp('6'),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },

  devider: {
    flex: 1,
    height: 1,
    backgroundColor: 'black',
    marginTop: hp('1'),
    marginBottom: hp('1'),
  },
  vendorLeftTextStyle: {
    fontWeight: 'bold',
    width: wp('20.5'),
    fontSize: hp('1.5'),
    color: 'black',
  },
  followViewContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    alignContent: 'center',
  },
  followButton: {
    backgroundColor: color.themColorPrimary,
    textAlign: 'center',
    padding: 10,
    // width: wp('30'),
    height: hp('5'),
    justifyContent: 'center',
    borderRadius: 5,
    marginLeft: 'auto',
    alignSelf: 'flex-end',
  },
  followText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: hp('2'),
  },
  followIcon: {
    marginLeft: wp('1'),
  },
  vendorRightText: {
    color: 'black',
    fontSize: hp('1.5'),
    width: wp('65'),
  },
  reviewInput: {
    borderWidth: 0.5,
    borderRadius: 5,
    paddingLeft: wp('5'),
    color: 'black',
    height: hp('6'),
    width: wp('85'),
    alignSelf: 'center',
  },
  reviewDescriptionInput: {
    borderWidth: 0.5,
    borderRadius: 5,
    paddingLeft: wp('5'),
    color: 'black',
    height: hp('8'),
    width: wp('85'),
    alignSelf: 'center',
    paddingTop: hp('1.1'),
  },
  vendorName: {
    color: color.defaultcolor,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    fontSize: hp('2.5'),
    width: wp('51'),
  },
});
