export const color = {
  statusbarColor: '#94725f',
  bottomNavColor: '#512500',
  defaultBackgroundColor: '#F6F6F6',
  defaultcolor: '#512500',
  textColorRedCart: '#B64400',
  redColor: 'red',
  // whatAppColor: 'green',
  whatAppColor: '#01430E',
  themColorPrimary: '#FF7E33',
  primaryBackground: 'white',
  cartIconsColor: '#FFDDC9',
  // primaryBackground: '#FFECCE',
  // primaryTabBackground: 'white',
  primaryTabBackground: '#E6CEAB',
};
