import {StyleSheet, Platform} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {color} from '../../config/color';

export const styles = StyleSheet.create({
  main: {
    backgroundColor: color.defaultBackgroundColor,
    // backgroundColor:"red",
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FFDDC9',
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 3},
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 21,
    height: hp(Platform?.OS == 'ios' ? '10' : '7'),
    alignItems: 'center',
  },
  te: {
    textAlign: 'center',
    fontSize: hp('2'),
    color: '#512500',
    fontWeight: 'bold',
    marginTop: hp(Platform?.OS == 'ios' ? '6' : '0'),
    marginLeft: wp('3'),
  },
  icon: {
    // margin: 20,
    marginTop: hp(Platform?.OS == 'ios' ? '5' : '0'),
    marginLeft: wp('3'),
    // marginLeft: wp(Platform?.OS == 'ios' ? '3' : '3'),
  },
  box: {
    padding: 13,
    backgroundColor: '#F3F5F7',
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowOffset: {width: 1, height: 1},
    shadowRadius: 2,
    elevation: 5,
    borderRadius: 10,
    width: wp('95'),
    alignSelf: 'center',
    marginBottom: hp('2'),
    marginTop: hp('2'),
  },
  container: {
    borderWidth: 0,
    borderBottomWidth: 1,
  },
  verticleLine: {
    height: 30,
    width: 1,
    backgroundColor: '#909090',
    marginTop: hp('2'),
    marginLeft: 10,
    marginRight: 10,
  },
  ty: {
    marginLeft: 'auto',
    color: 'gray',
    fontSize: hp('2%'),
  },
  maior: {
    width: wp('70%'),
    height: hp('6%'),
    backgroundColor: '#FF7E33',
    alignItems: 'center',
    marginTop: 42,
    borderRadius: 10,
    alignContent: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  or: {
    textAlign: 'center',
    fontSize: 16,
    color: 'white',
    justifyContent: 'center',
    fontWeight: 'bold',
    alignContent: 'center',
    alignItems: 'center',
  },
  imm: {
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginTop: hp('20%'),
  },
  tee: {
    color: '#512500',
    fontSize: 20,
    marginBottom: 10,
  },
  remov: {
    color: '#B64400',
    fontSize: 16,
    // fontWeight: 'bold',
    top: hp('2.5'),
  },
  buttonstyle: {
    width: wp('20%'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomimages: {
    borderColor: 'black',
    borderRadius: 10,
    borderWidth: 1,
    marginRight: 10,
  },
  imagss: {
    width: wp('27%'),
    height: hp('15%'),
    borderRadius: 10,
  },
  recentTextContainer: {
    width: wp('90%'),
    height: hp('5%'),
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  bottomImageScroller: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 20,
    marginTop: hp('3%'),
  },
  sliderText: {
    fontSize: hp('2%'),
    color: color.themColorPrimary,
  },
  checkBox: {
    width: wp('8'),
    marginLeft: wp('-4'),
    height: hp('3.8'),
  },
  insideContainer: {
    flexDirection: 'row',
    width: wp('95'),
    marginTop: hp('2'),
    alignSelf: 'center',
    alignItems: 'center',
  },
  selectText: {
    marginLeft: Platform.OS == 'ios' ? wp('3') : wp('0'),
    fontSize: hp('1.8'),
    fontWeight: 'bold',
  },
  imageStyle: {
    width: wp('27'),
    height: hp('12'),
    borderRadius: 10,
  },
  productNameStyle: {
    width: wp('40%'),
    fontSize: hp('1.8'),
    color: color.textColorRedCart,
    marginLeft: 10,
    marginBottom: hp('1'),
    fontWeight: 'bold',
  },
  productDiscountPriceStyle: {
    fontSize: hp('2'),
    color: 'red',
    marginLeft: wp('2'),
  },
  productPriceStyle: {
    fontSize: hp('2'),
    color: color.textColorRedCart,
    marginBottom: hp('1'),
  },
  attributeStyle: {
    fontSize: hp('2'),
    color: '#512500',
    marginLeft: 10,
  },
  attributeViewStyleValue: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: wp('35'),
  },
  attributeStyleValue: {
    fontSize: hp('1.9'),
    color: color.bottomNavColor,
    marginLeft: wp('1'),
    alignItems: 'center',
  },
  heartIconicContainer: {
    flex: 1,
    height: 2,
    backgroundColor: '#C8C8C8',
    marginTop: hp('1'),
  },
  decrementViewButton: {
    marginLeft: 'auto',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  incrementViewButton: {
    paddingTop: hp(Platform?.OS == 'ios' ? '2.3' : '2'),
    marginRight: 10,
    fontSize: hp('2.5'),
    color: '#EEB08B',
    fontWeight: 'bold',
  },
  logoutImageContainer: {
    width: wp('30%'),
    height: hp('15%'),
    borderRadius: 10,
  },
  logoutNameContainer: {
    width: wp('40%'),
    fontSize: hp('1.8'),
    color: color.textColorRedCart,
    marginLeft: 10,
    marginBottom: hp('1'),
    fontWeight: 'bold',
  },
  logoutPriceContainer: {
    fontSize: hp('2'),
    color: '#512500',
    marginLeft: 10,
    marginBottom: hp('1'),
  },
  logoutPriceValueContainer: {
    fontSize: hp('2'),
    color: '#512500',
    textDecorationLine: 'line-through',
  },
});
