import {StyleSheet, Platform} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {alignItems} from 'styled-system';
import {color} from '../../config/color';

export const styles = StyleSheet.create({
  main: {
    backgroundColor: color.defaultBackgroundColor,
    // backgroundColor:"white",

    flex: 1,
  },

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FFDDC9',
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 3},
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 5,
    height: hp(Platform?.OS == 'ios' ? '10' : '8'),
  },
  te: {
    textAlign: 'center',
    fontSize: 18,
    color: '#512500',
    fontWeight: 'bold',
    marginTop: hp(Platform?.OS == 'ios' ? '6' : '3'),
    marginLeft: wp('3'),
  },
  icon: {
    // margin: 20,
    marginTop: hp(Platform?.OS == 'ios' ? '5' : '2'),
    marginLeft: wp('3'),
    // marginLeft: wp(Platform?.OS == 'ios' ? '3' : '3'),
  },
  box: {
    padding: 13,
    margin: wp('7'),
    marginBottom: hp('1'),
    backgroundColor: 'white',
    //     backgroundColor: '#F3F5F7',
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowOffset: {width: 1, height: 3},
    shadowRadius: 2,
    elevation: 5,
    // height: hp('30'),
    borderRadius: 10,
  },
  topMain: {
    flexDirection: 'row',
    //     backgroundColor:"yellow",
    justifyContent: 'space-around',
    marginTop: wp('5'),
    width: wp('95'),
    alignSelf: 'center',
    marginBottom: wp('3'),
  },
  topButtonInactive: {
    width: wp('22'),
    backgroundColor: 'white',
    textAlign: 'center',
    alignItems: 'center',
    height: hp('5'),
    justifyContent: 'center',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'gray',
  },
  topButtonInactiveText: {
    color: 'gray',
    fontSize: hp('1.7'),
  },
  topButtonActive: {
    width: wp('22'),
    backgroundColor: '#FF7E33',
    textAlign: 'center',
    alignItems: 'center',
    height: hp('5'),
    justifyContent: 'center',
    borderRadius: 7,
  },
  topButtonActiveText: {
    color: 'white',
    fontSize: hp('1.7'),
  },
  centerText: {
    marginLeft: wp('8'),
    color: color.defaultcolor,
    marginTop: wp('4'),
  },
  text: {
    //     backgroundColor: '#F3F5F7',
    backgroundColor: 'white',
    height: hp('8'),
    width: wp('75'),
    alignSelf: 'center',
    fontSize: hp('2.5'),
    //     marginLeft:wp('4%')
  },
  radioText: {
    // marginTop: hp('0.9'),
    color: color.defaultcolor,
    marginLeft: wp('3'),
  },
  subtotalText: {
    color: color.defaultcolor,
    fontWeight: 'bold',
    fontSize: hp(1.8),
  },
  subtotalPrice: {
    marginLeft: 'auto',
    color: color.defaultcolor,
    fontWeight: 'bold',
    fontSize: hp(1.8),
  },
  maior: {
    width: wp('65%'),
    height: hp('6%'),
    backgroundColor: '#FF7E33',
    alignItems: 'center',
    marginBottom: hp('5'),
    marginTop: hp('5'),
    borderRadius: 10,
    alignContent: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  bottomBackButtonContainer: {
    width: wp('20%'),
    height: hp('6%'),
    backgroundColor: '#FF7E33',
    alignItems: 'center',
    marginBottom: hp('5'),
    marginTop: hp('5'),
    marginHorizontal: wp('1'),
    borderRadius: 10,
    alignContent: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  or: {
    textAlign: 'center',
    fontSize: 16,
    color: 'white',
    justifyContent: 'center',
    fontWeight: 'bold',
    alignContent: 'center',
    alignItems: 'center',
  },
  devider: {
    flex: 1,
    height: 1,
    backgroundColor: 'black',
    marginTop: hp('1'),
    marginBottom: hp('1'),
  },
  parentCardIconHolder: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'space-between',
    // backgroundColor: 'red',
    width: wp('83'),
    marginTop: hp('1'),
    // paddingTop: hp('0.5'),
    // paddingBottom: hp('0.7'),
  },
  iconStyle: {
    marginBottom: hp('0.8'),
  },
  parentCardRow: {
    width: wp('75'),
    // backgroundColor: 'yellow',
    flexDirection: 'row',
    // marginTop: hp('1.8'),
    alignItems: 'center',
    justifyContent: 'space-between',
    // alignSelf: 'center',
    borderBottomWidth: hp('0.2'),
    borderBottomColor: '#C8C8C8',
    paddingBottom: hp('0.7'),
    // marginTop: hp('1.5'),
  },
  parentCarddTextStyle: {
    fontSize: hp('1.8'),
    color: '#512500',
    // marginLeft: wp('3%'),
    // marginTop: hp('1.8'),
  },
  parentCarddTextStyle: {
    fontSize: hp('1.8'),
    color: '#512500',
    // marginLeft: wp('3%'),
    // marginTop: hp('1.8'),
  },
  payButton: {
    width: wp('70%'),
    height: hp('6%'),
    backgroundColor: color.themColorPrimary,
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: hp('2'),
    marginBottom: hp('2'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  payButtonText: {
    color: 'white',
    fontSize: hp('1.7'),
  },
  checkBoxButtonContainer: {
    marginTop: hp('2'),
    marginLeft: wp('7'),
  },
  checkStyle: {
    borderWidth: 0.5,
    borderColor: color.themColorPrimary,
    borderRadius: 60,
    width: wp('8.5'),
    height: hp('4.1'),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp('2'),
  },
  buttonstyle: {
    width: wp('20%'),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color.textColorRedCart,
  },
});
