import {Platform, StyleSheet} from 'react-native';
import {color} from '../../config/color';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  appbarStyle: {
    backgroundColor: '#FFDDC9',
    // paddingBottom: hp('5'),
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 3},
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 5,
    height: hp(Platform?.OS == 'ios' ? '16' : '15'),
  },
  head: {
    textAlign: 'center',
    // marginBottom: 10,
    marginBottom: hp(Platform?.OS == 'ios' ? '0' : '1'),

    fontWeight: '400',
    fontSize: 18,
    color: '#512500',
    marginTop: hp(Platform?.OS == 'ios' ? '4.5' : '1'),
  },
  search: {
    width: wp('80%'),
    backgroundColor: 'white',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 17,
    marginLeft: wp('2%'),
    marginTop: hp(Platform?.OS == 'ios' ? '2' : '0'),
  },
  searchbar: {
    width: wp('70%'),
    height: hp('6%'),
    backgroundColor: 'white',
    borderRadius: 17,
    paddingLeft: 15,
    color: '#512500',
  },
  box: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#F3F5F7',
    // marginRight: wp('3%'),
    shadowColor: '#000',
    // width:354,
    shadowOffset: {width: 1, height: 3},
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 5,
    marginBottom: 10,
    marginTop: hp('2'),
  },
  im: {
    width: wp('41'),
    height: hp('15'),
    borderRadius: 30,
    // shadowColor: '#000',
    // width:354,
    // shadowOffset: { width: 1, height: 1 },
    // shadowOpacity: 0.6,
    // shadowRadius: 18,
    // elevation: 5,
  },
  fea: {
    marginLeft: 10,
    marginTop: 10,
    backgroundColor: '#b64400',
    color: 'white',
    width: wp('15%'),
    borderRadius: 10,
    textAlign: 'center',
    fontSize: 10,
  },
  icons: {
    marginTop: 'auto',
    marginLeft: 5,
    width: wp('9%'),
  },
  text: {
    color: '#512500',
    fontSize: 16,
    paddingTop: hp('2%'),
    paddingLeft: wp('2%'),
  },
  imm: {
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginTop: hp('20%'),
  },
  tee: {
    color: '#512500',
    fontSize: hp('3'),
    marginBottom: 10,
    textAlign: 'center',
  },
  maior: {
    width: wp('70%'),
    height: hp('6%'),
    backgroundColor: '#FF7E33',
    alignItems: 'center',
    marginTop: 42,
    borderRadius: 10,
    alignContent: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  or: {
    textAlign: 'center',
    fontSize: 16,
    color: 'white',
    justifyContent: 'center',
    fontWeight: 'bold',
    alignContent: 'center',
    alignItems: 'center',
  },
  filterView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: wp('90'),
    alignSelf: 'center',
    marginTop: hp('2'),
    // marginBottom: hp('1'),
  },
  filterText: {color: '#512500', fontSize: hp('2.5'), fontWeight: 'bold'},
});
