export default {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  NO_INTERNET: 'NO_INTERNET',
  SAVEPRODUCT: 'SAVEPRODUCT',
  UNSAVEPRODUCT: 'UNSAVEPRODUCT',
  CLEAR_SAVE_PRODUCT: 'CLEAR_SAVE_PRODUCT',
  CHANGELANGUAGE: 'CHANGELANGUAGE',
  TOURCOMPLETED: 'TOURCOMPLETED',
  TOURCOMPLETEDLANGUAGE: 'TOURCOMPLETEDLANGUAGE',
  // GETPRODUCT:"GETPRODUCT"
};
