export default {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  NO_INTERNET: 'NO_INTERNET',
  SAVEPRODUCT: 'SAVEPRODUCT',
  UNSAVEPRODUCT: 'UNSAVEPRODUCT',
  // GETPRODUCT:"GETPRODUCT"
};
